### ISSUE TITLE
Launch ticket Sales

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#72]
- [ ] Specify a Ticket Registration launch date - 1 Feb 2016
- [ ] Specify ticket types and ticket prices
- [ ] Specify capacity for each ticket type
- [ ] Specify discount codes, hidden tickets, etc.
- [ ] Write welcome emails sent when registration is confirmed

**Comment by nathenharvey** [comment]
target a total of 500 tickets inclusive of staff, speakers, sponsors, press, government attendees, and regular attendees.

**Comment by mbarbine** [comment]
1. Can we have a box for whether an attendee is planning on getting lodging so that we can accurately block out hotels with an accurate attrition? and how many days of lodging. 

2. Can we get a checkbox to determine whether the attendees will attend an evening event? Would also effect obligation and attrition costs if we had some data on this. 

@nathenharvey @gallimorej

**Comment by gallimorej** [comment]
BusyConf is setup and ready to go live on 1 Feb 2016. @mbarbine, I added two custom questions for lodging and event attendance to be filled out when registering.
