### ISSUE TITLE
Purchase Walkie Talkies for the event

### ISSUE THREAD

**Issue by nathenharvey** [DevOpsDaysDC/planning#79]

**Comment by mbarbine** [comment]
I think 12 radios should be enough. 8 radios + 4 extra. The extra could be for times when we need more people with radios moving the crowds out of the common area and also to have a few charging while others are in use so that they ca be swapped. 

Thoughts? I'll find and purchase them if that sounds good. Let me know if we need to increase / decrease  etc.

**Comment by mbarbine** [comment]
@nathenharvey

**Comment by jsmartin** [comment]
My main concern here is the range and any approval we may need to use these things in the building.  It's mostly an open area, so before we buy them all, maybe we should test out a couple?

**Comment by nathenharvey** [comment]
I know the founder of http://www.orionlabs.co/ quite well.  Let me reach out to him and see if he'd be willing to loan us a set of Onyx for the event.  They work with bluetooth and your cell phone.

**Comment by nathenharvey** [comment]
Thoughts?  do we really need these or do you think we'll have sufficient coverage from volunteers and organizers on the ground.  Slack + push notifications may be enough.

**Comment by radiocats** [comment]
I think we are ok without walkie talkies.
Mike 

    On Friday, May 27, 2016 10:41 PM, Nathen Harvey <notifications@github.com> wrote:
 

 Thoughts? do we really need these or do you think we'll have sufficient coverage from volunteers and organizers on the ground. Slack + push notifications may be enough.—

**Comment by nathenharvey** [comment]
Let's go with Slack and use the green room as a "show office".

Robert Treat will print out contact cards.
